@startuml
class Core{
+calculateDifference(Map/List) : Map/List

}

interface Connection{
+sendMsg(Msg) : Boolean
+doPost(File) : Boolean
+doGet(path) : File
}

interface FileSystemProvider{
+getFileList(): Map/List
}

Core <-- Connection
Core <-- FileSystemProvider

@enduml