@startuml
interface Listener{
-Handler
--
+ Listener(handler, socket)
--
+ listen() : String
+ stop() : Boolean
}

interface Handler{
-DAO
--
+evaluateRequest(req)
}

interface DAO{
+doGet(path) : File
+doPost(file) : Boolean
}

Listener <-- Handler
DAO --> Handler

@enduml